# AwesomeTTS text-to-speech add-on website
#
# Copyright (C) 2014       Anki AwesomeTTS Development Team
# Copyright (C) 2014       Dave Shifflett
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

application: ankiatts
version: local
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 12h

handlers:
- url: /
  static_files: index.html
  upload: index\.html
  mime_type: text/html; charset=utf-8
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: 35d
  secure: always

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: 35d
  secure: always

- url: /style\.css
  static_files: style.css
  upload: style\.css
  secure: always

#- url: /api/update/[a-z\d]+-1\.0\.0
#  static_files: api/update/good-version.json
#  upload: api/update/good-version\.json
#  secure: always

#- url: /api/update/[a-z\d]+-1\.0\.0-(dev|pre)
#  static_files: api/update/need-newer.json  # edit details w/ each release
#  upload: api/update/need-newer\.json
#  secure: always

- url: /api/update/[a-z\d]+-\d+\.\d+\.\d+-(dev|pre)
  static_files: api/update/unreleased.json
  upload: api/update/unreleased\.json
  secure: always

- url: /api/update
  static_files: api/update/index.json
  upload: api/update/index\.json
  expiration: 35d
  secure: always

- url: /api
  static_files: api/index.json
  upload: api/index\.json
  expiration: 35d
  secure: always

- url: /[aA][pP][iI](/.*)?
  script: unresolved.api
  secure: always

- url: .*
  script: unresolved.other
  secure: always
